<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\aisp.Common\aisp.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Tokenizers.DotNet.runtime.linux-x64" Version="1.4.1" />
    <PackageReference Include="Tokenizers.DotNet.runtime.win-x64" Version="1.4.1" />
  </ItemGroup>

</Project>
