// <auto-generated />
using System;
using AISpace.Common.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AISpace.Common.DAL.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20260723084552_MapLinkYawDegrees")]
    partial class MapLinkYawDegrees
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AISpace.Common.DAL.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("TEXT");

                    b.Property<uint>("BloodType")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CharadollPersonality")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)2);

                    b.Property<int?>("CircleId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("CurrentMapId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("FaceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Hairstyle")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("HomeIslandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Like1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Like2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Like3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LikeDesc1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LikeDesc2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LikeDesc3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CircleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.CharacterEquipment", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId", "SlotIndex");

                    b.HasIndex("ItemId");

                    b.ToTable("CharacterEquipment", (string)null);
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.CharacterEventStatus", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId", "EventKey");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterEventStatuses", (string)null);
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.CharacterInventory", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("CharacterId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("CharacterInventory", (string)null);
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.Circle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeaderCharacterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Circles", (string)null);
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.GameChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelNum")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("CurrentUsers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<uint>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10990100u);

                    b.Property<uint>("MaxUsers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1000u);

                    b.Property<ushort>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Channels", (string)null);
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IconId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Socket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.Map", b =>
                {
                    b.Property<long>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Island")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SpawnRotation")
                        .HasColumnType("INTEGER");

                    b.Property<float>("SpawnX")
                        .HasColumnType("REAL");

                    b.Property<float>("SpawnY")
                        .HasColumnType("REAL");

                    b.Property<float>("SpawnZ")
                        .HasColumnType("REAL");

                    b.HasKey("MapId");

                    b.ToTable("Maps", (string)null);
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.MapLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Behavior")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Depth")
                        .HasColumnType("REAL");

                    b.Property<string>("DestinationMapIds")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DestinationSpawnRotation")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("DestinationSpawnX")
                        .HasColumnType("REAL");

                    b.Property<float?>("DestinationSpawnY")
                        .HasColumnType("REAL");

                    b.Property<float?>("DestinationSpawnZ")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Length")
                        .HasColumnType("REAL");

                    b.Property<float>("PositionX")
                        .HasColumnType("REAL");

                    b.Property<float>("PositionY")
                        .HasColumnType("REAL");

                    b.Property<float>("PositionZ")
                        .HasColumnType("REAL");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceMapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Yaw")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceMapId", "ChannelId", "SortOrder");

                    b.ToTable("MapLinks", (string)null);
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.Npc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(-1);

                    b.Property<DateTime>("DateEndUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999));

                    b.Property<DateTime>("DateStartUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc));

                    b.Property<int>("DayPhase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(-1);

                    b.Property<string>("EventKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventKind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("InteractionType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<long>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("NpcObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rotation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShopId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<float>("X")
                        .HasColumnType("REAL");

                    b.Property<float>("Y")
                        .HasColumnType("REAL");

                    b.Property<float>("Z")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("NpcObjectId")
                        .IsUnique();

                    b.HasIndex("ShopId");

                    b.HasIndex("MapId", "SortOrder");

                    b.ToTable("Npcs", (string)null);
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.NpcEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NpcId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NpcId", "SlotIndex")
                        .IsUnique();

                    b.ToTable("NpcEquipment", (string)null);
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.PendingMapTransfer", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<uint>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rotation")
                        .HasColumnType("INTEGER");

                    b.Property<float>("X")
                        .HasColumnType("REAL");

                    b.Property<float>("Y")
                        .HasColumnType("REAL");

                    b.Property<float>("Z")
                        .HasColumnType("REAL");

                    b.HasKey("UserId");

                    b.HasIndex("ExpiresAtUtc");

                    b.ToTable("PendingMapTransfers", (string)null);
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.SessionPresence", b =>
                {
                    b.Property<Guid>("ConnectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rotation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("X")
                        .HasColumnType("REAL");

                    b.Property<float>("Y")
                        .HasColumnType("REAL");

                    b.Property<float>("Z")
                        .HasColumnType("REAL");

                    b.HasKey("ConnectionId");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("ServerType", "CharacterId");

                    b.HasIndex("ServerType", "UserId");

                    b.HasIndex("ServerType", "MapId", "ChannelId");

                    b.ToTable("SessionPresences", (string)null);
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BannerVisualId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Shops", (string)null);
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AiPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NicoPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<int>("ShopId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShopId", "ItemId")
                        .IsUnique();

                    b.HasIndex("ShopId", "SortOrder");

                    b.ToTable("ShopItems", (string)null);
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AiPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<string>("BanReason")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BannedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<long>("NicoPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OTP")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OTP")
                        .IsUnique();

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.World", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Worlds");
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.Character", b =>
                {
                    b.HasOne("AISpace.Common.DAL.Entities.Circle", "Circle")
                        .WithMany()
                        .HasForeignKey("CircleId");

                    b.HasOne("AISpace.Common.DAL.Entities.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.CharacterEquipment", b =>
                {
                    b.HasOne("AISpace.Common.DAL.Entities.Character", "Character")
                        .WithMany("Equipment")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AISpace.Common.DAL.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.CharacterEventStatus", b =>
                {
                    b.HasOne("AISpace.Common.DAL.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.CharacterInventory", b =>
                {
                    b.HasOne("AISpace.Common.DAL.Entities.Character", "Character")
                        .WithMany("Inventory")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AISpace.Common.DAL.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.Npc", b =>
                {
                    b.HasOne("AISpace.Common.DAL.Entities.Shop", "Shop")
                        .WithMany("Npcs")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.NpcEquipment", b =>
                {
                    b.HasOne("AISpace.Common.DAL.Entities.Npc", "Npc")
                        .WithMany("Equipment")
                        .HasForeignKey("NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Npc");
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.ShopItem", b =>
                {
                    b.HasOne("AISpace.Common.DAL.Entities.Shop", "Shop")
                        .WithMany("Items")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.UserSession", b =>
                {
                    b.HasOne("AISpace.Common.DAL.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.Character", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.Npc", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.Shop", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Npcs");
                });

            modelBuilder.Entity("AISpace.Common.DAL.Entities.User", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
